/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockStakingSol from "./MockStaking.sol";
export type { mockStakingSol };
import type * as delegation from "./delegation";
export type { delegation };
export type { TestToken } from "./TestToken";
