name: floe_staking
author: waterlily_zhou
version: 0.1.0
description: Pool allocation strategies, auto claiming and restaking on Balancer protocols.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeigkh3bwwjzgbl3jlcbovrf67ikisndygihsutgqlijhgie3z44ao4
fingerprint_ignore_patterns: []
agent: waterlily_zhou/floe_staking_agent:0.1.0
number_of_agents: 1
deployment: {}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${ETH_MAINNET_RPC:str:http://localhost:8545}
      chain_id: ${ETH_CHAIN_ID:int:1}
      poa_chain: ${IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
---
public_id: valory/configs:0.19.0
type: connection
config:
  ETH_MAINNET_RPC: ${ETH_MAINNET_RPC:str:}
  PRIVATE_KEY: ${PRIVATE_KEY:str:}
  THRESHOLD_AMOUNT: ${THRESHOLD_AMOUNT:str:1.0}
  MAINNET_STAKING_ADDRESS: ${MAINNET_STAKING_ADDRESS:str:}
  CLAUDE_API_KEY: ${CLAUDE_API_KEY:str:}
  ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY:str:}
