/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockStakingSol from "./MockStaking.sol";
export * as delegation from "./delegation";
export { TestToken__factory } from "./TestToken__factory";
