agent_name: floe_staking
author: waterlily_zhou
version: 0.1.0
license: Apache-2.0
description: Pool allocation strategies, auto claiming and restaking on Balancer protocols.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeida7kayw4iuc4vxqxnjyononicx4fuuseqyu3koxsb7o2hwbtnojy
fingerprint_ignore_patterns: []
connections: []
contracts: []
protocols: []
skills: []
customs: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-cosmos:
    version: ==1.63.0
  open-aea-ledger-ethereum:
    version: ==1.63.0
default_connection: null
